- name: Add DataDog keys to keyring
  ansible.builtin.apt_key:
    url: https://keys.datadoghq.com/{{ item }}.public
    keyring: /usr/share/keyrings/datadog-archive-keyring.gpg
  with_items:
    - DATADOG_APT_KEY_CURRENT
  become: yes
  tags:
    - linux
    - debian
- name: Add DataDog apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/datadog-archive-keyring.gpg] https://apt.datadoghq.com/ stable 7"
    state: present
  become: yes
  tags:
    - linux
    - debian
- name: Install DataDog agent
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - datadog-agent
    - datadog-signing-keys
  become: yes
  tags:
    - linux
    - debian
- name: Copia file di configurazione
  ansible.builtin.copy:
    src: /etc/datadog-agent/datadog.yaml.example
    dest: /etc/datadog-agent/datadog.yaml
    remote_src: yes
  become: yes
  tags:
    - linux
    - debian
- name: Copia datadog.yaml
  ansible.builtin.replace:
    path: /etc/datadog-agent/datadog.yaml
    regexp:  "{{ item.search }}"
    replace: "{{ item.replace }}"
  become: yes
  with_items:
  - { search: "api_key:\n", replace: "api_key: \n" }
  - { search: "# site: datadoghq.com\n", replace: "site: datadoghq.eu\n" }
  - { search: "# env: <environment name>\n", replace: "env: uat\n" }
  tags:
    - linux
    - debian
- name: Aggiunta dei tag
  lineinfile:
    path: /etc/datadog-agent/datadog.yaml
    line: "{{ item }}"
    insertafter: EOF
    state: present
  become: yes
  with_items:
    - "tags: [team:bmit]"
  tags:
    - linux
    - debian
- name: Start datadog agent
  ansible.builtin.systemd:
    state: started
    name: datadog-agent
  become: yes
  tags:
    - linux
    - debian
  